# Generated by Django 4.2.7 on 2024-02-13 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default image', upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.CharField(choices=[('LIKE', 'Нравится'), ('DISLIKE', 'Не нравится')], default='LIKE', max_length=7, verbose_name='Лайки'),
        ),
    ]
