# Generated by Django 4.2.7 on 2024-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_article_date_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/images/', verbose_name='Изображение'),
        ),
    ]
