# Generated by Django 4.2.7 on 2024-02-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_author_options_article_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(choices=[('Алёна', 'Алёна')], null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
    ]
