# Generated by Django 4.2.7 on 2024-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_account_alter_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category_id',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='news.category'),
        ),
    ]
