# Generated by Django 4.2.7 on 2024-02-26 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desciption', models.TextField()),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='cat',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='articles.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default value', upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.CharField(choices=[('LIKE', 'Нравится'), ('DISLIKE', 'Не нравится')], default='LIKE', max_length=7, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='default title', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.author'),
        ),
    ]
