# Generated by Django 4.2.7 on 2024-02-26 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_anons_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='articles.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.CharField(blank=True, choices=[('LIKE', 'Нравится'), ('DISLIKE', 'Не нравится')], default='LIKE', max_length=7, null=True, verbose_name='Лайки'),
        ),
    ]
